/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.xmumcarpick;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.HeadlessException;
import java.io.*;
import java.net.*;
import java.util.ArrayList;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Francis
 */
public class CarPickClient extends javax.swing.JFrame {

    /**
     * Creates new form CarPickClient
     */
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    DefaultTableModel model = new DefaultTableModel();
    XMUMCarPick OOP = new XMUMCarPick();
    String username, address = "localhost";
    ArrayList<String> userss = new ArrayList();
    
   
    
    
    Boolean isConnected = false;
    Socket theSocket;
    BufferedReader theReader;
    PrintWriter theWriter;
    
    public void ListenThread(){
        Thread IncomingReader = new Thread(new typeArea());
        IncomingReader.start();
    }
    
    public void userAdd(String data){
        userss.add(data);
    }
    
    public void userRemove(String data){
        showArea.append(data + " is now offline! \n");
    }
    
    public void writeUsers(){
        String[] tempList = new String[(userss.size())];
        userss.toArray(tempList);
        for(String token : tempList){
            
        }
    }
    
    public void sendDisconnect(){
        String bye = (username + ": :Disconnect");
        try{
            theWriter.println(bye);
            theWriter.flush();
            
        }catch(Exception ex){
            showArea.append("You're not connected!");
        }
    }
    
    public void Disconnect(){
        try{
            showArea.append("Disconnected... \n");
            theSocket.close();
        }catch(Exception ex){
            
        }
        isConnected = false;
        clientname.setEditable(true);
    }
    
    public CarPickClient() {
        
        initComponents();
        
        Object col[] = {"Name", "Origin","Destination","Pax","Time","Date"};
        model.setColumnIdentifiers(col);
        jTable1.setModel(model);
        con = CarPickClient.ConnectDB();
        
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        clientname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        showArea = new javax.swing.JTextArea();
        connect = new javax.swing.JButton();
        disconnect = new javax.swing.JButton();
        typeArea = new javax.swing.JTextField();
        send = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        add = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        nameArea = new javax.swing.JTextField();
        origin = new javax.swing.JLabel();
        originArea = new javax.swing.JTextField();
        destination = new javax.swing.JLabel();
        destinationArea = new javax.swing.JTextField();
        destination1 = new javax.swing.JLabel();
        paxArea = new javax.swing.JTextField();
        destination2 = new javax.swing.JLabel();
        dateArea = new javax.swing.JTextField();
        destination3 = new javax.swing.JLabel();
        timeArea = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(17, 76, 195));
        setForeground(new java.awt.Color(203, 75, 75));

        jPanel1.setBackground(new java.awt.Color(126, 193, 245));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        clientname.setText("Your Name");
        clientname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientnameActionPerformed(evt);
            }
        });
        clientname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                clientnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                clientnameKeyTyped(evt);
            }
        });

        showArea.setColumns(20);
        showArea.setRows(5);
        jScrollPane1.setViewportView(showArea);

        connect.setBackground(new java.awt.Color(0, 204, 102));
        connect.setBorder(null);
        connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectActionPerformed(evt);
            }
        });

        disconnect.setBackground(new java.awt.Color(255, 51, 51));
        disconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectActionPerformed(evt);
            }
        });

        typeArea.setText("Type your message here...");
        typeArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeAreaActionPerformed(evt);
            }
        });
        typeArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                typeAreaKeyReleased(evt);
            }
        });

        send.setBackground(new java.awt.Color(51, 102, 255));
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(typeArea)
                        .addGap(18, 18, 18)
                        .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(clientname, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(connect, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(disconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clientname, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(connect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(disconnect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(send, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(typeArea, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(98, 98, 98))
        );

        jPanel2.setBackground(new java.awt.Color(41, 142, 230));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        jTable1.setBorder(new javax.swing.border.MatteBorder(null));
        jTable1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Origin", "Destination", "Pax", "Date", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setFont(new java.awt.Font("Monospaced", 3, 12)); // NOI18N
        add.setForeground(new java.awt.Color(51, 153, 255));
        add.setText("ADD ORDER");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Monospaced", 3, 12)); // NOI18N
        delete.setForeground(new java.awt.Color(51, 153, 255));
        delete.setText("DELETE ORDER");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Monospaced", 3, 12)); // NOI18N
        update.setForeground(new java.awt.Color(51, 153, 255));
        update.setText("UPDATE TABLE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        refresh.setBackground(new java.awt.Color(255, 255, 255));
        refresh.setFont(new java.awt.Font("Monospaced", 3, 12)); // NOI18N
        refresh.setForeground(new java.awt.Color(51, 153, 255));
        refresh.setText("RESET COLUMNS");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        name.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        name.setText("Name");

        nameArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameAreaActionPerformed(evt);
            }
        });

        origin.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        origin.setText("Origin");

        originArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                originAreaActionPerformed(evt);
            }
        });

        destination.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        destination.setText("Destination");

        destinationArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationAreaActionPerformed(evt);
            }
        });

        destination1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        destination1.setText("Pax");

        paxArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paxAreaActionPerformed(evt);
            }
        });

        destination2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        destination2.setText("Depart Date");

        dateArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateAreaActionPerformed(evt);
            }
        });

        destination3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        destination3.setText("Depart Time");

        timeArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(origin, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(destination, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(destination1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(destination2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(destination3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(destinationArea, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(originArea, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameArea, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paxArea, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateArea, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeArea, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 21, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(nameArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(origin)
                    .addComponent(originArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destination)
                    .addComponent(destinationArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destination1)
                    .addComponent(paxArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destination2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destination3)
                    .addComponent(timeArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(delete)
                    .addComponent(update)
                    .addComponent(refresh))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jPanel3.setBackground(new java.awt.Color(49, 75, 255));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("XMUMCarPick");

        exit.setBackground(new java.awt.Color(255, 0, 0));
        exit.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 0, 0));
        exit.setText("LOGOUT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jButton1.setText("Passenger");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(exit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static Connection ConnectDB(){
    try{
        Class.forName("org.sqlite.JDBC");
        Connection con = DriverManager.getConnection("jdbc:sqlite:dataform.db");
        return con;
    }catch(Exception ex){
        JOptionPane.showMessageDialog(null, ex);
        return null;
    }
}
    
public void updateTable(){
    con = CarPickClient.ConnectDB();
    if(con!=null){
        String sql = "SELECT Name, Origin, Destination, Pax, Time, Date FROM dataform";
        
        try{
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            Object[] columnData = new Object[6];
            
            while(rs.next()){
                columnData[0] = rs.getString("Name");
                columnData[1] = rs.getString("Origin");
                columnData[2] = rs.getString("Destination");
                columnData[3] = rs.getString("Pax");
                columnData[4] = rs.getString("Time");
                columnData[5] = rs.getString("Date");
                model.addRow(columnData);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }
    }
}
    
    private void connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectActionPerformed
        // TODO add your handling code here:
        switch(clientname.getText()){
            case "":
                clientname.setText("Input your name! \n");
                break;
            case "Your Name":
                clientname.setText("Input your name! \n");
                break;
            case "Input your name!":
                break;
            default:
                if(isConnected == false){
                    username = clientname.getText();
                    clientname.setEditable(false);
                    
                    try{
                        theSocket = new Socket("10.71.91.219", 60000);
                        InputStreamReader streamreader = new InputStreamReader(theSocket.getInputStream());
                        theReader = new BufferedReader (streamreader);
                        theWriter = new PrintWriter(theSocket.getOutputStream());
                        theWriter.println(username + ": has connected :Connect");
                        theWriter.flush();
                        isConnected = true;
                        
                    }catch(Exception ex){
                        showArea.append("Cannot connect! Try Again. \n");
                        clientname.setEditable(true);
                    }
                    ListenThread();
                }
                else if(isConnected == true){
                    showArea.append("You are connected to the server. \n");
                }
        }
    }//GEN-LAST:event_connectActionPerformed

    private void disconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectActionPerformed
        // TODO add your handling code here:
        sendDisconnect();
        Disconnect();
    }//GEN-LAST:event_disconnectActionPerformed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        // TODO add your handling code here:
        switch (typeArea.getText()){
            case "Your messages":
                typeArea.setText("Type your message here");
                typeArea.requestFocus();
            case "Client name":
                break;
            case "Input your name":
                break;
            default:
                try{
                    theWriter.println(username + " : " + typeArea.getText() + ":" + "Chat");
                    theWriter.flush();
                }catch(Exception ex){
                    showArea.append("You're not connected to the server! \n");
                }
                typeArea.setText("");
                typeArea.requestFocus();
        }
        typeArea.setText("Your messages");
        typeArea.requestFocus();
    }//GEN-LAST:event_sendActionPerformed

    private void typeAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeAreaActionPerformed
        // TODO add your handling code here:
        if(typeArea.getText().equals("Your messages")){
            typeArea.setText("");
        }
    }//GEN-LAST:event_typeAreaActionPerformed

    private void clientnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientnameActionPerformed
        // TODO add your handling code here:
        if(clientname.getText().equals("Your Name")){
            clientname.setText("");
        }
    }//GEN-LAST:event_clientnameActionPerformed

    private void clientnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clientnameKeyTyped
        // TODO add your handling code here:
        switch(clientname.getText()){
            case "Your Name":
                clientname.setText("");
                break;
            case "Input your name!":
                clientname.setText("");
            default:
        }
    }//GEN-LAST:event_clientnameKeyTyped

    private void clientnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clientnameKeyReleased
        // TODO add your handling code here:
        switch (clientname.getText()){
            case "":
                
            default:
                String name = clientname.getText();
                String result = name.substring(0,1).toUpperCase() + name.substring(1);
                clientname.setText(result);
        }
    }//GEN-LAST:event_clientnameKeyReleased

    private void typeAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_typeAreaKeyReleased
        // TODO add your handling code here:
        switch(typeArea.getText()){
            
            default:
                String name = typeArea.getText();
                String result = name.substring(0,1).toUpperCase() + name.substring(1);
                typeArea.setText(result);
        }
    }//GEN-LAST:event_typeAreaKeyReleased

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        DefaultTableModel mod = (DefaultTableModel) jTable1.getModel();
        mod.setRowCount(0);
        SimpleDateFormat Dformat = new SimpleDateFormat("dd-MM-yyyy");
        String sql = "INSERT INTO dataform(Name, Origin, Destination, Pax, Time, Date)VALUES(?,?,?,?,?,?)";
        
        try{
            pst = con.prepareStatement(sql);
            
            pst.setString(1, nameArea.getText());
            pst.setString(2, originArea.getText());
            pst.setString(3, destinationArea.getText());
            pst.setString(4, paxArea.getText());
            pst.setString(5, timeArea.getText());
            pst.setString(6, dateArea.getText());
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "System Updated");
            rs.close();
            pst.close();
            
        }
        catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
            updateTable();
            
            DefaultTableModel iModel = (DefaultTableModel) jTable1.getModel();
            if(jTable1.getSelectedRow()==-1){
                if(jTable1.getRowCount() == 0){
                    JOptionPane.showMessageDialog(null, "Dara Entry Update Confirmed!", "XMUMCarPick Form", JOptionPane.OK_OPTION);
                }
            }
    }//GEN-LAST:event_addActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();
        String cell = jTable1.getModel().getValueAt(row, 4).toString();
        String sql = "DELETE FROM dataform WHERE Time = " + cell;
        if(jTable1.getSelectedRow()==-1){
            if(jTable1.getRowCount()==0){
                JOptionPane.showMessageDialog(null, "No order to be selected! ", "XMUMCarPick Passenger Form", JOptionPane.OK_OPTION);
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Select a order to delete ", "XMUMCarPick Passenger Form", JOptionPane.OK_OPTION);
                
            }
        }
        else{
            
            try{
                pst=con.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Order Deleted Successfully!");
                
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }finally{
                try{
                    pst.close();
                    rs.close();
                }catch (Exception ex){
                    
                }
            }
        }
        model.setRowCount(0);
        updateTable();
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        //DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        /*mod.setRowCount(0);/*
        
        String sql = "INSERT INTO dataform(Name, Origin, Destination, Pax, Time, Date)VALUES(?,?,?,?,?,?)";
        
        try{
            pst = con.prepareStatement(sql);
            
            pst.setString(1, nameArea.getText());
            pst.setString(2, originArea.getText());
            pst.setString(3, destinationArea.getText());
            pst.setString(4, paxArea.getText());
            pst.setString(5, timeArea.getText());
            pst.setString(6, dateArea.getText());
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "System Updated");
            rs.close();
            pst.close();
            
        }
        catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }*/
            /*String sql = "DELETE FROM dataform";
            try{
                pst = con.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "System Updated");
                rs.close();
                pst.close();
            }catch(HeadlessException | SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
            }*/
            model.setRowCount(0);
            updateTable();
            
            DefaultTableModel iModel = (DefaultTableModel) jTable1.getModel();
            if(jTable1.getSelectedRow()==-1){
                if(jTable1.getRowCount() == 0){
                    JOptionPane.showMessageDialog(null, "Order has been taken! ", "XMUMCarPick Form", JOptionPane.OK_OPTION);
                }
            }
    }//GEN-LAST:event_updateActionPerformed

    private void nameAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameAreaActionPerformed

    private void originAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_originAreaActionPerformed

    private void destinationAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinationAreaActionPerformed

    private void paxAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paxAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paxAreaActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        try{
            nameArea.setText(null);
            originArea.setText(null);
            destinationArea.setText(null);
            paxArea.setText(null);
            dateArea.setText(null);
            timeArea.setText(null);
        }catch(Exception ex){
            
        }
    }//GEN-LAST:event_refreshActionPerformed

    private void dateAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateAreaActionPerformed

    private void timeAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeAreaActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        new CarPickLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_exitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
private JFrame frame;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarPickClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarPickClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarPickClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarPickClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarPickClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField clientname;
    private javax.swing.JButton connect;
    private javax.swing.JTextField dateArea;
    private javax.swing.JButton delete;
    private javax.swing.JLabel destination;
    private javax.swing.JLabel destination1;
    private javax.swing.JLabel destination2;
    private javax.swing.JLabel destination3;
    private javax.swing.JTextField destinationArea;
    private javax.swing.JButton disconnect;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameArea;
    private javax.swing.JLabel origin;
    private javax.swing.JTextField originArea;
    private javax.swing.JTextField paxArea;
    private javax.swing.JButton refresh;
    private javax.swing.JButton send;
    private javax.swing.JTextArea showArea;
    private javax.swing.JTextField timeArea;
    private javax.swing.JTextField typeArea;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    public class typeArea implements Runnable{
    @Override
    public void run(){
        String[] data;
        String stream;
        
        try{
            while(!(stream = theReader.readLine()).equals(null)){
                data = stream.split(":");
                
                switch(data[2]){
                    case "Chat":
                        showArea.append(data[0] + ":" + data[1] + "\n");
                        showArea.setCaretPosition(showArea.getDocument().getLength());
                        break;
                    case "Connect":
                        showArea.removeAll();
                        userAdd(data[0]);
                        break;
                    case "Disconnect":
                        userRemove(data[0]);
                        break;
                    case "Done":
                        writeUsers();
                        userss.clear();
                }
            }
        }
            catch (Exception ex){
                    
                    }
        }
    }
}

